#!/bin/bash

TODAY=$(date +%Y%m%d_%H%M%S)

OUTPUT_DIR="/home/monalisa/issmon_data/power_index"
mkdir -p "${OUTPUT_DIR}"

FILETMP="${OUTPUT_DIR}/${TODAY}.txt"

PDU="172.20.0.192"
SNMP_COMMUNITY="-t 5 -r 1 -c iss-ro -v 2c"
ARGS=" -OQs "

## PowerNet-MIB::isxModularDistModuleOutputKwhUsage
OID_PW_USAGE=".1.3.6.1.4.1.318.1.1.22.2.6.1.21"

## seconds since the Epoch (1970-01-01 00:00 UTC)
echo "TIMESTAMP=$(date +%s)" > ${FILETMP}
snmpbulkwalk ${ARGS} ${SNMP_COMMUNITY} ${PDU} ${OID_PW_USAGE} | sed 's/isxModularDistModuleOutputKwhUsage./BR_/g;s/\./_/g;s/ //g' >> ${FILETMP} 2>/dev/null

