#!/usr/bin/env bash

exec 300<$0
flock -n 300 || exit 1

pushd /home/monalisa/issmon &> /dev/null || { echo "Could not pushd"; exit 1; }

/home/monalisa/issmon/get_PDUtable
/home/monalisa/bin/gmond_pdu

# do it last as is the slowest operation
/home/monalisa/issmon/write_status

popd &>/dev/null

