#!/bin/bash

ISSMON_DIR="/home/monalisa/issmon/"
DATADIR="/home/monalisa/issmon_data/raid_info"
ARCDIR="/home/raid_info"

RAID_HOSTS="eos_fst15"

for host in ${RAID_HOSTS} ; do
  SYNCDIR="${ARCDIR}"
  mkdir -p ${DATADIR}/${host}/
  rsync --min-size=10 -qauWz --delete ${host}:${SYNCDIR}/ ${DATADIR}/${host}/
done

