#!/bin/bash

TODAY=$(date +%Y%m%d_%H%M%S)

OUTPUT_DIR="/home/monalisa/issmon_data/power_index_tot"
mkdir -p "${OUTPUT_DIR}"

FILETMP="${OUTPUT_DIR}/${TODAY}.txt"

HOST="10.10.11.246"
SNMP_COMMUNITY="-t 5 -r 1 -c iss-ro -v 2c"
ARGS=" -OQs "

# JANITZA-MIB::whL1.0
# JANITZA-MIB::whL2.0
# JANITZA-MIB::whL3.0
# JANITZA-MIB::wh3.0
WHL1=".1.3.6.1.4.1.34278.3.1.0"
WHL2=".1.3.6.1.4.1.34278.3.2.0"
WHL3=".1.3.6.1.4.1.34278.3.3.0"
WH_TOT=".1.3.6.1.4.1.34278.4.1.0"

# JANITZA-MIB::qhL1.0
# JANITZA-MIB::qhL2.0
# JANITZA-MIB::qhL3.0
# JANITZA-MIB::qh3.0
QHL1=".1.3.6.1.4.1.34278.3.4.0"
QHL2=".1.3.6.1.4.1.34278.3.5.0"
QHL3=".1.3.6.1.4.1.34278.3.6.0"
QH_TOT=".1.3.6.1.4.1.34278.4.2.0"

PW_USAGE="${WHL1} ${WHL2} ${WHL3} ${WH_TOT} ${QHL1} ${QHL2} ${QHL3} ${QH_TOT}"

## seconds since the Epoch (1970-01-01 00:00 UTC)
echo "TIMESTAMP=$(date +%s)" > ${FILETMP}
snmpget ${ARGS} ${SNMP_COMMUNITY} ${HOST} ${PW_USAGE}  | sed 's/\.0//g;s/\./_/g;s/ //g' >> ${FILETMP} 2>/dev/null

