#!/bin/bash

# SMART ATTRIB
# 1   - Raw Read Error Rate
# 5   - Reallocated Sector Count
# 7   - Seek Error Rate
# 194 - Temperature
# 196 - Reallocation Event Count
# 197 - Current Pending Sector Count
# 198 - Off-line Scan Uncorrectable

get_smart_from_file () {
  awk '{
      if ( $1 == 1 )   {print $1, "Raw_Read_Error_Rate", $(NF-4), $(NF-1);}
      if ( $1 == 5 )   {print $1, "Reallocated_Sector_Count", $(NF-4), $(NF-1);}
      if ( $1 == 7 )   {print $1, "Seek_Error_Rate", $(NF-4), $(NF-1);}
      if ( $1 == 194 ) {print $1, "Temperature", $(NF-4), $(NF-1);}
      if ( $1 == 196 ) {print $1, "Reallocation_Event_Count", $(NF-4), $(NF-1);}
      if ( $1 == 197 ) {print $1, "Current_Pending_Sector_Count", $(NF-4), $(NF-1);}
      if ( $1 == 198 ) {print $1, "Off-line_Scan_Uncorrectable", $(NF-4), $(NF-1);}
    }' $1
}

ISSMON_DIR="/export/home/monalisa/issmon/"
DATADIR="/export/home/monalisa/issmon_data/raid_smart"
RAWDATADIR=${DATADIR}/raw

RAID_HOSTS="issaf storage02 storage03 storage04 storage05 storage06 storage07"

SMART_DIR="raid_info/smart"

for host in $RAID_HOSTS ; do
  if [ "$host" == "issaf" ] ; then
    BASEDIR="/export/"
  else
    BASEDIR="/home/"
  fi

  mkdir -p $RAWDATADIR/$host
  rsync --min-size=10 -qauWz --delete ${host}:${BASEDIR}/${SMART_DIR}/ ${RAWDATADIR}/${host}/
done

for server_dirs in ${RAWDATADIR}/* ; do
  server=$(basename ${server_dirs})
  SHORTDIR="${DATADIR}/short/${server}"
  mkdir -p ${SHORTDIR}

  for hdd in ${server_dirs}/* ; do
    [[ -e ${hdd} ]] || continue
    get_smart_from_file ${hdd} | column -t > $SHORTDIR/$(basename ${hdd})
  done
done

