#!/usr/bin/env bash

exec 300<$0
flock -n 300 || exit 1

#MYDIR="$(basename $(readlink -f ${BASH_SOURCE}))"
#pushd "${MYDIR}" &> /dev/null

pushd /home/monalisa/issmon &> /dev/null || { echo "Could not pushd"; exit 1; }

/home/monalisa/issmon/get_ups_data &
/home/monalisa/issmon/get_PDUtable &
/home/monalisa/issmon/get_cooling_data &
wait

# Send ganglia metrics
/home/monalisa/bin/gmond_ups &
/home/monalisa/bin/gmond_pdu &
/home/monalisa/bin/gmond_cooling &
wait

# do it last as is the slowest operation
/home/monalisa/issmon/write_status

popd &>/dev/null

