#!/bin/bash

PWD_DIR=`dirname $0`

PDU="172.20.0.192"

OUTPUT_DIR="/export/home/monalisa/issmon_data"

TEMP_FILE="/tmp/temp_snmp_data.txt"

FILE="$OUTPUT_DIR/PDUtable.txt"
FILE_SHORT="$OUTPUT_DIR/PDU.txt"

GET="snmpget"
TABLE="snmptable"

SNMP_COMMUNITY="-c iss-ro -v 2c -Pu"
ARG3="-Oqv"
TABLE_ARGS="-Os -Le -Cl -Cb"

NAME=".1.3.6.1.2.1.1.5.0"
POWERNET=".1.3.6.1.4.1.318"

BREAKER_TABLE=".1.1.22.2.4"

## isxModularDistModuleBreakerTable
${TABLE} ${TABLE_ARGS} ${SNMP_COMMUNITY} ${PDU} ${POWERNET}${BREAKER_TABLE}  > ${FILE}

tail -n +4 $FILE | sed 's/phaseL//g' | awk \
'{
if ($1 != "-1")
  {
  br="BR_"$1"_"$2"_";
  printf ( br"I=%.1f \n"br"Load=%.1f \n"br"Power=%.1f \n\n", $9/10, $10/10, $11/10 );
  }
}' > ${FILE_SHORT}
