#!/bin/bash

exec 200<$0
flock -n 200 || exit 1

DAY=$(date +%d.%m.%Y)
TIME=$(date +%k:%M:%S%Z)

NOW="${DAY}  ${TIME}"

CURL_CMD="/usr/bin/curl -fsSLk -o"

ISSMON_DIR="/home/monalisa/issmon"
OUTPUT_DIR="/home/monalisa/issmon/data"

FILE_TEMPLATE="${ISSMON_DIR}/ISS-DC_template.png"
FILE="${OUTPUT_DIR}/ISS-DC_tmp.png"
FILE_FINAL="${OUTPUT_DIR}/ISS-DC.png"

TMP1="${ISSMON_DIR}/tmp1.png"

cp ${FILE_TEMPLATE} ${FILE}

source ${OUTPUT_DIR}/UPS.txt
source ${OUTPUT_DIR}/PDU.txt

load_total=$(echo "$UPS_OUT_LOAD1 + $UPS_OUT_LOAD2 + $UPS_OUT_LOAD3" | bc -l)

##   FUNCTIONS
pprint4 () { local val=$(printf "%04.1f\n" $1); echo "${val}"; } 

br_load_temp_color () {
local value=""
(( $(echo "$1 < 50"  | bc -l) )) && { value="black -font Liberation-Sans";     }
(( $(echo "$1 >= 50" | bc -l) )) && { value="SeaGreen -font Liberation-Sans";  }
(( $(echo "$1 >= 70" | bc -l) )) && { value="orange -font Liberation-Sans-Bold";    }
(( $(echo "$1 >= 80" | bc -l) )) && { value="OrangeRed -font Liberation-Sans-Bold"; }
(( $(echo "$1 >= 90" | bc -l) )) && { value="red1 -font Liberation-Sans-Bold";      }
echo $value
}

temp_color_sup () {
local value=""
(( $(echo "$1 < 21"  | bc -l) )) && { value="navy -font Liberation-Sans";     }
(( $(echo "$1 >= 21" | bc -l) )) && { value="SeaGreen -font Liberation-Sans";  }
(( $(echo "$1 >= 23" | bc -l) )) && { value="orange -font Liberation-Sans-Bold";    }
(( $(echo "$1 >= 25" | bc -l) )) && { value="OrangeRed -font Liberation-Sans-Bold"; }
(( $(echo "$1 >= 27" | bc -l) )) && { value="red1 -font Liberation-Sans-Bold";      }
echo $value
}

temp_color_inlet () {
local value=""
(( $(echo "$1 < 23"  | bc -l) )) && { value="navy -font Liberation-Sans";     }
(( $(echo "$1 >= 23" | bc -l) )) && { value="SeaGreen -font Liberation-Sans";  }
(( $(echo "$1 >= 25" | bc -l) )) && { value="orange -font Liberation-Sans-Bold";    }
(( $(echo "$1 >= 27" | bc -l) )) && { value="OrangeRed -font Liberation-Sans-Bold"; }
(( $(echo "$1 >= 29" | bc -l) )) && { value="red1 -font Liberation-Sans-Bold";      }
echo $value
}

temp_color_ret () {
local value=""
(( $(echo "$1 < 27"  | bc -l) )) && { value="navy -font Liberation-Sans";     }
(( $(echo "$1 >= 27" | bc -l) )) && { value="SeaGreen -font Liberation-Sans";  }
(( $(echo "$1 >= 32" | bc -l) )) && { value="orange -font Liberation-Sans-Bold";    }
(( $(echo "$1 >= 35" | bc -l) )) && { value="OrangeRed -font Liberation-Sans-Bold"; }
(( $(echo "$1 >= 38" | bc -l) )) && { value="red1 -font Liberation-Sans-Bold";      }
echo $value
}

COLOR="blue"

###############################################################################################################
COLOR_1_1=$(br_load_temp_color $BR_1_1_Load)
COLOR_1_2=$(br_load_temp_color $BR_1_2_Load)
COLOR_1_3=$(br_load_temp_color $BR_1_3_Load)
COLOR_2_1=$(br_load_temp_color $BR_2_1_Load)
COLOR_2_2=$(br_load_temp_color $BR_2_2_Load)
COLOR_2_3=$(br_load_temp_color $BR_2_3_Load)
COLOR_18_1=$(br_load_temp_color $BR_18_1_Load)
COLOR_18_2=$(br_load_temp_color $BR_18_2_Load)
COLOR_18_3=$(br_load_temp_color $BR_18_3_Load)
COLOR_19_1=$(br_load_temp_color $BR_19_1_Load)
COLOR_19_2=$(br_load_temp_color $BR_19_2_Load)
COLOR_19_3=$(br_load_temp_color $BR_19_3_Load)
COLOR_20_1=$(br_load_temp_color $BR_20_1_Load)
COLOR_20_2=$(br_load_temp_color $BR_20_2_Load)
COLOR_20_3=$(br_load_temp_color $BR_20_3_Load)
COLOR_21_1=$(br_load_temp_color $BR_21_1_Load)
COLOR_21_2=$(br_load_temp_color $BR_21_2_Load)
COLOR_21_3=$(br_load_temp_color $BR_21_3_Load)
COLOR_22_1=$(br_load_temp_color $BR_22_1_Load)
COLOR_22_2=$(br_load_temp_color $BR_22_2_Load)
COLOR_22_3=$(br_load_temp_color $BR_22_3_Load)
COLOR_23_1=$(br_load_temp_color $BR_23_1_Load)
COLOR_23_2=$(br_load_temp_color $BR_23_2_Load)
COLOR_23_3=$(br_load_temp_color $BR_23_3_Load)
COLOR_24_1=$(br_load_temp_color $BR_24_1_Load)
COLOR_24_2=$(br_load_temp_color $BR_24_2_Load)
COLOR_24_3=$(br_load_temp_color $BR_24_3_Load)

###############################################################################################################
convert -size 840x1010 xc:"rgba(0,0,0,0)" -type truecolormatte PNG32:${TMP1}
convert -transparent white -alpha transparent \
-fill ${COLOR_1_1}  -pointsize 16 -gravity west -annotate +0+0   "BR_01_1_I = $BR_1_1_Power kW   --> $(pprint4 $BR_1_1_Load) %" \
-fill ${COLOR_1_2}  -pointsize 16 -gravity west -annotate +0+19  "BR_01_2_I = $BR_1_2_Power kW   --> $(pprint4 $BR_1_2_Load) %" \
-fill ${COLOR_1_3}  -pointsize 16 -gravity west -annotate +0+38  "BR_01_3_I = $BR_1_3_Power kW   --> $(pprint4 $BR_1_3_Load) %" \
-fill ${COLOR_2_1}  -pointsize 16 -gravity west -annotate +0+57  "BR_02_1_I = $BR_2_1_Power kW   --> $(pprint4 $BR_2_1_Load) %" \
-fill ${COLOR_2_2}  -pointsize 16 -gravity west -annotate +0+76  "BR_02_2_I = $BR_2_2_Power kW   --> $(pprint4 $BR_2_2_Load) %" \
-fill ${COLOR_2_3}  -pointsize 16 -gravity west -annotate +0+95  "BR_02_3_I = $BR_2_3_Power kW   --> $(pprint4 $BR_2_3_Load) %" \
-fill ${COLOR_18_1} -pointsize 16 -gravity west -annotate +0+114 "BR_18_1_I = $BR_18_1_Power kW   --> $(pprint4 $BR_18_1_Load) %" \
-fill ${COLOR_18_2} -pointsize 16 -gravity west -annotate +0+133 "BR_18_2_I = $BR_18_2_Power kW   --> $(pprint4 $BR_18_2_Load) %" \
-fill ${COLOR_18_3} -pointsize 16 -gravity west -annotate +0+152 "BR_18_3_I = $BR_18_3_Power kW   --> $(pprint4 $BR_18_3_Load) %" \
-fill ${COLOR_19_1} -pointsize 16 -gravity west -annotate +0+171 "BR_19_1_I = $BR_19_1_Power kW   --> $(pprint4 $BR_19_1_Load) %" \
-fill ${COLOR_19_2} -pointsize 16 -gravity west -annotate +0+190 "BR_19_2_I = $BR_19_2_Power kW   --> $(pprint4 $BR_19_2_Load) %" \
-fill ${COLOR_19_3} -pointsize 16 -gravity west -annotate +0+209 "BR_19_3_I = $BR_19_3_Power kW   --> $(pprint4 $BR_19_3_Load) %" \
-fill ${COLOR_20_1} -pointsize 16 -gravity west -annotate +0+228 "BR_20_1_I = $BR_20_1_Power kW   --> $(pprint4 $BR_20_1_Load) %" \
-fill ${COLOR_20_2} -pointsize 16 -gravity west -annotate +0+247 "BR_20_2_I = $BR_20_2_Power kW   --> $(pprint4 $BR_20_2_Load) %" \
-fill ${COLOR_20_3} -pointsize 16 -gravity west -annotate +0+266 "BR_20_3_I = $BR_20_3_Power kW   --> $(pprint4 $BR_20_3_Load) %" \
-fill ${COLOR_21_1} -pointsize 16 -gravity west -annotate +0+285 "BR_21_1_I = $BR_21_1_Power kW   --> $(pprint4 $BR_21_1_Load) %" \
-fill ${COLOR_21_2} -pointsize 16 -gravity west -annotate +0+304 "BR_21_2_I = $BR_21_2_Power kW   --> $(pprint4 $BR_21_2_Load) %" \
-fill ${COLOR_21_3} -pointsize 16 -gravity west -annotate +0+323 "BR_21_3_I = $BR_21_3_Power kW   --> $(pprint4 $BR_21_3_Load) %" \
-fill ${COLOR_22_1} -pointsize 16 -gravity west -annotate +0+342 "BR_22_1_I = $BR_22_1_Power kW   --> $(pprint4 $BR_22_1_Load) %" \
-fill ${COLOR_22_2} -pointsize 16 -gravity west -annotate +0+361 "BR_22_2_I = $BR_22_2_Power kW   --> $(pprint4 $BR_22_2_Load) %" \
-fill ${COLOR_22_3} -pointsize 16 -gravity west -annotate +0+380 "BR_22_3_I = $BR_22_3_Power kW   --> $(pprint4 $BR_22_3_Load) %" \
-fill ${COLOR_23_1} -pointsize 16 -gravity west -annotate +0+399 "BR_23_1_I = $BR_23_1_Power kW   --> $(pprint4 $BR_23_1_Load) %" \
-fill ${COLOR_23_2} -pointsize 16 -gravity west -annotate +0+418 "BR_23_2_I = $BR_23_2_Power kW   --> $(pprint4 $BR_23_2_Load) %" \
-fill ${COLOR_23_3} -pointsize 16 -gravity west -annotate +0+437 "BR_23_3_I = $BR_23_3_Power kW   --> $(pprint4 $BR_23_3_Load) %" \
-fill ${COLOR_24_1} -pointsize 16 -gravity west -annotate +0+456 "BR_24_1_I = $BR_24_1_Power kW   --> $(pprint4 $BR_24_1_Load) %" \
-fill ${COLOR_24_2} -pointsize 16 -gravity west -annotate +0+475 "BR_24_2_I = $BR_24_2_Power kW   --> $(pprint4 $BR_24_2_Load) %" \
-fill ${COLOR_24_3} -pointsize 16 -gravity west -annotate +0+494 "BR_24_3_I = $BR_24_3_Power kW   --> $(pprint4 $BR_24_3_Load) %" \
-trim ${TMP1} ${TMP1}




############################################################
#### TEMPERATURES
# CLIMA4
source ${OUTPUT_DIR}/cooling/172.20.0.184.cooling
ret4=${Return_temp}
sup4=${Supply_temp}
inlet4=${Rack_inlet_temp}

# CLIMA3
source ${OUTPUT_DIR}/cooling/172.20.0.183.cooling
ret3=${Return_temp}
sup3=${Supply_temp}
inlet3=${Rack_inlet_temp}

# CLIMA2
source ${OUTPUT_DIR}/cooling/172.20.0.182.cooling
ret2=${Return_temp}
sup2=${Supply_temp}
inlet2=${Rack_inlet_temp}

# CLIMA5
source ${OUTPUT_DIR}/cooling/172.20.0.185.cooling
ret5=${Return_temp}
sup5=${Supply_temp}
inlet5=${Rack_inlet_temp}

# CLIMA1
source ${OUTPUT_DIR}/cooling/172.20.0.181.cooling
ret1=${Return_temp}
sup1=${Supply_temp}
inlet1=${Rack_inlet_temp}

# CLIMA6
source ${OUTPUT_DIR}/cooling/172.20.0.186.cooling
ret6=${Return_temp}
sup6=${Supply_temp}
inlet6=${Rack_inlet_temp}

#############################

COLOR_S1=$(temp_color_sup $sup1)
COLOR_S2=$(temp_color_sup $sup2)
COLOR_S3=$(temp_color_sup $sup3)
COLOR_S4=$(temp_color_sup $sup4)
COLOR_S5=$(temp_color_sup $sup5)
COLOR_S6=$(temp_color_sup $sup6)

COLOR_I1=$(temp_color_inlet $inlet1)
COLOR_I2=$(temp_color_inlet $inlet2)
COLOR_I3=$(temp_color_inlet $inlet3)
COLOR_I4=$(temp_color_inlet $inlet4)
COLOR_I5=$(temp_color_inlet $inlet5)
COLOR_I6=$(temp_color_inlet $inlet6)

COLOR_R1=$(temp_color_ret $ret1)
COLOR_R2=$(temp_color_ret $ret2)
COLOR_R3=$(temp_color_ret $ret3)
COLOR_R4=$(temp_color_ret $ret4)
COLOR_R5=$(temp_color_ret $ret5)
COLOR_R6=$(temp_color_ret $ret6)

BAT_STATUS="OK"
BAT_COLOR="green1"
[[ "${BAT_Replace}" != "noBatteryNeedsReplacing" ]] && { BAT_STATUS="FAIL" ; BAT_COLOR="red1"; }

COLOR="black"

convert \
-font Liberation-Sans-Bold -fill black -pointsize 24 -annotate +1150+40 "${NOW}" \
-font Liberation-Sans -fill ${COLOR} -pointsize 18             -annotate +1118+531 $BAT_Cap \
-font Liberation-Sans-Bold -fill ${BAT_COLOR} -pointsize 18    -annotate +1103+553 $BAT_STATUS \
-font Liberation-Sans -fill ${COLOR}    -pointsize 18          -annotate +1160+574 $BAT_Temp \
-font Liberation-Sans -fill ${COLOR}    -pointsize 18          -annotate +1108+596 $BAT_Runtime \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+45+240   "20_2 =  $BR_20_2_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+128+240  "21_2 =  $BR_21_2_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+196+240 'CLIMA 4' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+257+240  "20_3 =  $BR_20_3_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+340+240  "21_3 =  $BR_21_3_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+470+240  "19_1 =  $BR_19_1_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+556+240  "18_1 =  $BR_18_1_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+621+240 'CLIMA 3' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+680+240  "19_3 =  $BR_19_3_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+766+240  "18_3 =  $BR_18_3_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+836+240 'CLIMA 6' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+895+240  "19_2 =  $BR_19_2_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+980+240  "18_2 =  $BR_18_2_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+45+790   "23_3 =  $BR_23_3_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+128+790  "24_3 =  $BR_24_3_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+196+790 'CLIMA 1' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+257+790  "24_2 =  $BR_24_2_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+340+790  "23_2 =  $BR_23_2_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+414+790 'CLIMA 5' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+470+790  "24_1 =  $BR_24_1_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+470+1010 "20_1 =  $BR_20_1_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+556+1010 "21_1 =  $BR_21_1_Load %" \
-font Liberation-Sans -fill black       -pointsize 19 -annotate 270x270+621+790 'CLIMA 2' \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+680+790  "23_1 =  $BR_23_1_Load %" \
-font Liberation-Sans -fill ${COLOR}    -pointsize 19 -annotate 270x270+766+790  "22_2 =  $BR_22_2_Load %" \
-font Liberation-Sans -fill ${COLOR_S4} -pointsize 16 -annotate +148+25 $sup4 \
-font Liberation-Sans -fill ${COLOR_I4} -pointsize 16 -annotate +148+45 $inlet4 \
-font Liberation-Sans -fill ${COLOR_R4} -pointsize 16 -annotate +172+549 $ret4 \
-font Liberation-Sans -fill ${COLOR_S3} -pointsize 16 -annotate +572+25 $sup3 \
-font Liberation-Sans -fill ${COLOR_I3} -pointsize 16 -annotate +572+45 $inlet3 \
-font Liberation-Sans -fill ${COLOR_R3} -pointsize 16 -annotate +596+549 $ret3 \
-font Liberation-Sans -fill ${COLOR_S6} -pointsize 16 -annotate +783+25 $sup6 \
-font Liberation-Sans -fill ${COLOR_I6} -pointsize 16 -annotate +783+45 $inlet6 \
-font Liberation-Sans -fill ${COLOR_R6} -pointsize 16 -annotate +808+549 $ret6 \
-font Liberation-Sans -fill ${COLOR_R1} -pointsize 16 -annotate +170+594 $ret1 \
-font Liberation-Sans -fill ${COLOR_S1} -pointsize 16 -annotate +131+1081 $sup1 \
-font Liberation-Sans -fill ${COLOR_I1} -pointsize 16 -annotate +131+1101 $inlet1 \
-font Liberation-Sans -fill ${COLOR_R5} -pointsize 16 -annotate +390+594 $ret5 \
-font Liberation-Sans -fill ${COLOR_S5} -pointsize 16 -annotate +347+1081 $sup5 \
-font Liberation-Sans -fill ${COLOR_I5} -pointsize 16 -annotate +347+1101 $inlet5 \
-font Liberation-Sans -fill ${COLOR_R2} -pointsize 16 -annotate +594+594 $ret2 \
-font Liberation-Sans -fill ${COLOR_S2} -pointsize 16 -annotate +569+1081 $sup2 \
-font Liberation-Sans -fill ${COLOR_I2} -pointsize 16 -annotate +569+1101 $inlet2 \
${FILE} ${FILE}

convert -gravity east \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +37-493 "$UPS_OUT_LOAD1_P100" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +98-493 "$UPS_OUT_LOAD1" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +37-471 "$UPS_OUT_LOAD2_P100" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +98-471 "$UPS_OUT_LOAD2" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +37-449 "$UPS_OUT_LOAD3_P100" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +98-449 "$UPS_OUT_LOAD3" \
-font Liberation-Sans-Bold -fill ${COLOR} -pointsize 20 -annotate +98-419 "$load_total" \
${FILE} ${FILE}

##   add power info per Breaker
composite -geometry +1230+180  ${TMP1} ${FILE} ${FILE}
############################################################################

#CPU_REPORT="${ISSMON_DIR}/cpu_report.png"
#LOAD_REPORT="${ISSMON_DIR}/load_report.png"
#MEM_REPORT="${ISSMON_DIR}/mem_report.png"
#NET_REPORT="${ISSMON_DIR}/network_report.png"
#POWER_REPORT="${ISSMON_DIR}/power_report.png"

#CPU_REPORT_CROP="${ISSMON_DIR}/cpu_report_crop.png"
#LOAD_REPORT_CROP="${ISSMON_DIR}/load_report_crop.png"
#MEM_REPORT_CROP="${ISSMON_DIR}/mem_report_crop.png"
#NET_REPORT_CROP="${ISSMON_DIR}/network_report_crop.png"
#POWER_REPORT_CROP="${ISSMON_DIR}/power_report_crop.png"

#supply_view_12h="http://monitor.spacescience.ro/ganglia/graph.php?r=12hr&z=xlarge&hreg[]=clima%5B1-6%5D&mreg[]=supply.temp&gtype=line&vl=C&title=Supply+Temp&aggregate=1"
#return_view_12h="http://monitor.spacescience.ro/ganglia/graph.php?r=12hr&z=xlarge&hreg[]=clima%5B1-6%5D&mreg[]=return.temp&gtype=line&vl=C&title=Return+Temp&aggregate=1"

#inlet_pic_tmp="${ISSMON_DIR}/inlet_report.png"
#inlet_pic="${ISSMON_DIR}/inlet_report_crop.png"

#${CURL_CMD} ${inlet_pic_tmp} 'http://monitor.spacescience.ro/ganglia/graph.php?r=12hr&z=xlarge&hreg[]=clima%5B1-6%5D&mreg[]=rackinlet.temp&gtype=line&vl=C&title=Inlet+Temp&aggregate=1'
#convert ${inlet_pic_tmp} -crop +0-64 +repage -resize 35% ${inlet_pic}

# ${CURL_CMD} ${CPU_REPORT}   "https://monitor.spacescience.ro/ganglia/graph.php?r=day&z=xlarge&me=ISS-DATACENTER&m=load_one&s=by+name&mc=3&g=cpu_report"
# ${CURL_CMD} ${LOAD_REPORT}  "https://monitor.spacescience.ro/ganglia/graph.php?r=day&z=xlarge&me=ISS-DATACENTER&m=load_one&s=by+name&mc=3&g=load_report"
# ${CURL_CMD} ${MEM_REPORT}   "https://monitor.spacescience.ro/ganglia/graph.php?r=day&z=xlarge&me=ISS-DATACENTER&m=load_one&s=by+name&mc=3&g=mem_report"
# ${CURL_CMD} ${NET_REPORT}   "https://monitor.spacescience.ro/ganglia/graph.php?r=day&z=xlarge&me=ISS-DATACENTER&m=load_one&s=by+name&mc=3&g=network_report"
# ${CURL_CMD} ${POWER_REPORT} "https://monitor.spacescience.ro/ganglia/graph.php?r=day&z=xlarge&g=ups_kwp_report&h=ups-dc&c=ISS_UPS_Status"
# 
# convert ${LOAD_REPORT}  -crop +0-64 +repage -resize 35% ${LOAD_REPORT_CROP}
# convert ${MEM_REPORT}   -crop +0-90 +repage -resize 35% ${MEM_REPORT_CROP}
# convert ${NET_REPORT}   -crop +0-35 +repage -resize 27% ${NET_REPORT_CROP}
# convert ${POWER_REPORT} -crop +0-50 +repage -resize 50% ${POWER_REPORT_CROP}
# 
# composite -geometry +550+130  ${LOAD_REPORT_CROP} ${FILE} ${FILE}
# composite -geometry +550+260  ${MEM_REPORT_CROP} ${FILE} ${FILE}
# composite -geometry +550+20   ${NET_REPORT_CROP} ${FILE} ${FILE}
# composite -geometry +730+600   ${POWER_REPORT_CROP} ${FILE} ${FILE}

rm -f ${TMP1}
mv -f ${FILE} ${FILE_FINAL}








